### ISSUE TITLE
Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Uninitialized string offset: 0 in **/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php:79

### ISSUE THREAD

**Issue by anuri73** [egeloen/IvoryLuceneSearchBundle#17]
I am trying to index my data (about 25k rows), but on getting the following error:

`
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Uninitialized string offset: 0 in **//vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php:79
Stack trace:
#0 **/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php(121): ZendSearch\Lucene\Storage\File\AbstractFile->readInt()
#1 **/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index/Writer.php(395): ZendSearch\Lucene\Index::getActualGeneration(Object(ZendSearch\Lucene\Storage\Directory\Filesystem))
#2 **/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index/Writer.php(747): ZendSearch\Lucene\Index\Writer->_updateSegments()
#3 **/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php(1158): ZendSearch\Lucene\Index\Writer->commit()
#4 **/vendor/zendframework/zendsear in **//vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php on line 154
`

I am using Vagrant(Homestead). Inserting code is:
`
/**
	 * Persist Lucene index
	 *
	 * @param LuceneManager $lucene_manager
	 * @param string        $lucene_identifier
	 * @param Station       $station
	 *
	 * @return Document
	 */
	protected function persistLucene( LuceneManager $lucene_manager, string $lucene_identifier, Station $station ) {
		$document = new Document();
		$document->addField( Document\Field::keyword( 'station_code', $station->getStationCode() ) );
		$document->addField( Document\Field::text( 'station_name', $station->getStationNameFull() ) );
		$lucene_manager->getIndex( $lucene_identifier )->addDocument( $document );

		return $document;
	}
`

And the values are:

> 2000153,"ПОСТ 94 КМ"

**Comment by anuri73** [comment]
Also on trying to remove index directory from the console (`rm -rf **/var/lucene`) I am getting the error:
`rm: cannot remove 'var/lucene/station/segments.gen': Input/output error`
But I wasn't catching the following error before

**Comment by anuri73** [comment]
My composer.lock:
`
"name": "egeloen/lucene-search-bundle",
"version": "3.0.0",
`
`
"name": "zendframework/zendsearch",
"version": "dev-master",
`

**Comment by anuri73** [comment]
https://github.com/zendframework/ZendSearch/pull/8#issuecomment-230953378
